### ISSUE TITLE
Freeze when WAIT line is asserted and Step to next instruction is clicked

### ISSUE THREAD

**Issue by Calindro** [floooh/v6502r#22]
When the WAIT line is asserted and the "Step to next instruction" button is clicked, the whole application freezes.

**Comment by floooh** [comment]
Ouch yeah, that's because I do something really stupid here which ends up as an infinite loop if the CPU doesn't make progress:

https://github.com/floooh/v6502r/blob/bcedbdd9269459f8b58989877b688d494cdf3018/src/sim.c#L121-L125

Thanks for catching that, it will be a while until I get around fixing the issues though, I'm currently deep in other things.

**Comment by floooh** [comment]
Fixed in https://github.com/floooh/v6502r/commit/cf3b1495949b5e22fbcaac0510cfe002b2cccb16, if wait is active, op-stepping now only executes one half-cycle.
